line-length = 100

[lint]
select = [ "ALL" ]
ignore = [
    "D", # docstring checks
    "INP001", # add an __init__.py
    "FBT001", # boolean-typed argument in function def
    "FBT003", # boolean-typed argument in function call
    "PLR", # code complexity
    "C", # code complexity
    "ERA001", # commented-out code
    "T201", # `print` found
    "ANN101", # missing type annotation for 'self'
    "ANN204", # missing type annotation for __init__
]
